site_name: Oversight ICS
site_description: A comprehensive documentation suite for Oversight ICS - A Cognitive Reliability & Predictive Failover Agent for Industrial Control Systems
site_author: Amy Mummert

nav:
    - Home: index.md
    - Documentation Suite:
      - Glossary: glossary.md
      - Technical Deep Dive: oversight_ics_technical_deep_dive.md
      - System Architecture: system-architecture-overview-and-tradeoffs.md
      - Oversight Context View: oversight-c4-context-view.svg

theme:
    name: readthedocs
    navigation_depth: 4
    prev_next_buttons_location: top
    sticky_navigation: true
extra_css:
  - style.css